<?php

namespace Julio\Capyrel\Generators;

use Illuminate\Support\Str;
use Julio\Capyrel\Detectors\UploadColumnDetector;

/**
 * Generates a typed Axios/Fetch API service class for each model.
 *
 * Output: resources/ts/services/{Model}Service.ts
 *
 * Uses the interfaces from TypeScriptGenerator.
 * Works with any Axios instance — import and configure your own.
 */
class AxiosClientGenerator
{
    public function generate(string $modelName, array $columns, array $relationships): string
    {
        $route      = Str::kebab(Str::plural($modelName));
        $hasFiles   = !empty(UploadColumnDetector::collectFrom($columns));
        $hasBtm     = collect($relationships)->contains('type', 'belongsToMany');
        $hasSoft    = in_array('deleted_at', array_column($columns, 'name'));

        $toFormData  = $hasFiles  ? $this->buildToFormData()  : '';
        $restoreMeth = $hasSoft   ? $this->buildRestoreMethod($route, $modelName) : '';
        $bulkUpdate  = $hasBtm    ? $this->buildBulkUpdateMethod($route, $modelName) : '';

        return <<<TS
// Auto-generated by Capyrel. Do not edit manually.
import type {
  {$modelName},
  Create{$modelName}Payload,
  Update{$modelName}Payload,
  Paginated{$modelName},
  {$modelName}IndexParams,
} from '../models/{$modelName}';

// Swap this import for your own configured axios instance.
import axios from 'axios';

const BASE = '/{$route}';

/**
 * Fully-typed API client for {$modelName} resources.
 *
 * Usage:
 *   const { data } = await {$modelName}Service.index({ search: 'foo', page: 2 });
 *   const post = await {$modelName}Service.store({ title: 'Hello', body: '...' });
 */
export const {$modelName}Service = {

  /** GET /{$route} — paginated, filterable, sortable list. */
  index(params?: {$modelName}IndexParams): Promise<Paginated{$modelName}> {
    return axios.get(BASE, { params }).then(r => r.data);
  },

  /** GET /{$route}/:id — single resource, optional includes. */
  show(id: number, include?: string): Promise<{$modelName}> {
    return axios.get(`\${BASE}/\${id}`, { params: include ? { include } : {} }).then(r => r.data.data ?? r.data);
  },

  /** POST /{$route} — create a new resource. Handles file uploads automatically. */
  store(payload: Create{$modelName}Payload): Promise<{ message: string; data: {$modelName} }> {
    return axios.post(BASE, toFormData(payload), {
      headers: { 'Content-Type': 'multipart/form-data' },
    }).then(r => r.data);
  },

  /** PUT /{$route}/:id — update. Only sends changed fields. */
  update(id: number, payload: Update{$modelName}Payload): Promise<{ message: string; data: {$modelName} }> {
    const body = toFormData({ ...payload, _method: 'PUT' });
    return axios.post(`\${BASE}/\${id}`, body, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }).then(r => r.data);
  },

  /** DELETE /{$route}/:id */
  destroy(id: number): Promise<{ message: string }> {
    return axios.delete(`\${BASE}/\${id}`).then(r => r.data);
  },

  /** POST /{$route}/bulk-destroy — delete up to 100 records in one request. */
  bulkDestroy(ids: number[]): Promise<{ message: string }> {
    return axios.post(`\${BASE}/bulk-destroy`, { ids }).then(r => r.data);
  },

  /** GET /{$route} with include=rel1,rel2 shorthand. */
  withRelations(id: number, ...includes: string[]): Promise<{$modelName}> {
    return {$modelName}Service.show(id, includes.join(','));
  },

  /** Export current filtered set as a file download. */
  export(params?: {$modelName}IndexParams): void {
    const query = new URLSearchParams(params as Record<string, string>).toString();
    window.location.href = `\${BASE}/export?\${query}`;
  },
{$restoreMeth}{$bulkUpdate}};
{$toFormData}
TS;
    }

    private function buildToFormData(): string
    {
        return <<<TS

/** Recursively serialise a payload object to FormData, handling File objects. */
function toFormData(obj: Record<string, unknown>, form = new FormData(), prefix = ''): FormData {
  for (const [key, value] of Object.entries(obj)) {
    const field = prefix ? `\${prefix}[\${key}]` : key;
    if (value === undefined || value === null) continue;
    if (value instanceof File) {
      form.append(field, value);
    } else if (Array.isArray(value)) {
      value.forEach((v, i) => {
        if (v instanceof File) form.append(`\${field}[\${i}]`, v);
        else form.append(`\${field}[]`, String(v));
      });
    } else if (typeof value === 'object') {
      toFormData(value as Record<string, unknown>, form, field);
    } else {
      form.append(field, String(value));
    }
  }
  return form;
}
TS;
    }

    private function buildRestoreMethod(string $route, string $modelName): string
    {
        return <<<TS

  /** POST /{$route}/:id/restore — restore a soft-deleted record. */
  restore(id: number): Promise<{ message: string; data: {$modelName} }> {
    return axios.post(`\${BASE}/\${id}/restore`).then(r => r.data);
  },

  /** DELETE /{$route}/:id/force — permanently delete a soft-deleted record. */
  forceDelete(id: number): Promise<{ message: string }> {
    return axios.delete(`\${BASE}/\${id}/force`).then(r => r.data);
  },

TS;
    }

    private function buildBulkUpdateMethod(string $route, string $modelName): string
    {
        return <<<TS

  /** POST /{$route}/bulk-update — patch selected fields on multiple records. */
  bulkUpdate(ids: number[], attributes: Partial<Update{$modelName}Payload>): Promise<{ message: string }> {
    return axios.post(`\${BASE}/bulk-update`, { ids, attributes }).then(r => r.data);
  },

TS;
    }
}
