<?php

namespace Julio\Capyrel\Generators;

use Illuminate\Support\Str;

/**
 * Generates the real-time broadcasting stack for a model:
 *   App\Events\{Model}Created  (ShouldBroadcast)
 *   App\Events\{Model}Updated  (ShouldBroadcast)
 *   App\Events\{Model}Deleted  (ShouldBroadcast)
 *   App\Broadcasting\{Model}Channel
 *
 * Also outputs the routes/channels.php registration block.
 */
class BroadcastingGenerator
{
    public function generateEvent(string $modelName, string $action): string
    {
        $eventName   = $modelName . Str::studly($action);
        $variable    = Str::camel($modelName);
        $channelName = Str::kebab(Str::plural($modelName)) . '.{id}';

        return <<<PHP
<?php

namespace App\Events;

use App\Models\\{$modelName};
use App\Http\Resources\\{$modelName}Resource;
use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class {$eventName} implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public function __construct(public readonly {$modelName} \${$variable}) {}

    public function broadcastOn(): array
    {
        return [
            new PrivateChannel('{$channelName}'),
            new Channel('" . Str::kebab(Str::plural($modelName)) . "'),
        ];
    }

    public function broadcastAs(): string
    {
        return '{$modelName}.{$action}';
    }

    public function broadcastWith(): array
    {
        return [
            'event'  => '{$modelName}.{$action}',
            '{$variable}' => new {$modelName}Resource(\$this->{$variable}),
        ];
    }

    /** Only broadcast when the model has actually changed (update event). */
    public function broadcastWhen(): bool
    {
        return true;
    }
}
PHP;
    }

    public function generateChannel(string $modelName): string
    {
        $variable = Str::camel($modelName);

        return <<<PHP
<?php

namespace App\Broadcasting;

use App\Models\\{$modelName};
use App\Models\User;

class {$modelName}Channel
{
    /**
     * Authenticate the user's access to the channel.
     * Called for PrivateChannel and PresenceChannel.
     */
    public function join(User \$user, {$modelName} \${$variable}): bool
    {
        // Authorise: user can view this {$modelName}
        return \$user->can('view', \${$variable});
    }
}
PHP;
    }

    public function generateChannelsRegistration(array $modelNames): string
    {
        $lines = ['<?php', '', 'use Illuminate\Support\Facades\Broadcast;', ''];

        foreach ($modelNames as $modelName) {
            $route   = Str::kebab(Str::plural($modelName));
            $class   = "App\\Broadcasting\\{$modelName}Channel";
            $lines[] = "Broadcast::channel('{$route}.{id}', {$class}::class);";
        }

        return implode("\n", $lines);
    }

    public function generateFrontendListener(string $modelName): string
    {
        $route    = Str::kebab(Str::plural($modelName));
        $variable = Str::camel($modelName);

        return <<<TS
// resources/ts/broadcasting/{$modelName}Channel.ts
// Auto-generated by Capyrel. Requires Laravel Echo + Pusher/Ably/Reverb.
import Echo from 'laravel-echo';

declare const window: Window & { Echo: Echo };

/**
 * Subscribe to real-time {$modelName} updates.
 *
 * Usage:
 *   subscribe{$modelName}(42, {
 *     onUpdated: ({$variable}) => console.log('{$modelName} updated', {$variable}),
 *     onDeleted: ({$variable}) => console.log('{$modelName} deleted', {$variable}),
 *   });
 */
export function subscribe{$modelName}(
  id: number,
  handlers: {
    onCreated?: (data: unknown) => void;
    onUpdated?: (data: unknown) => void;
    onDeleted?: (data: unknown) => void;
  }
): () => void {
  const channel = window.Echo.private(`{$route}.\${id}`);

  if (handlers.onCreated) channel.listen('{$modelName}.created', handlers.onCreated);
  if (handlers.onUpdated) channel.listen('{$modelName}.updated', handlers.onUpdated);
  if (handlers.onDeleted) channel.listen('{$modelName}.deleted', handlers.onDeleted);

  // Return unsubscribe function
  return () => window.Echo.leave(`{$route}.\${id}`);
}

/** Subscribe to the public {$route} channel for list updates. */
export function subscribe{$modelName}List(
  onEvent: (event: string, data: unknown) => void
): () => void {
  const channel = window.Echo.channel('{$route}');
  channel
    .listen('{$modelName}.created', (d: unknown) => onEvent('created', d))
    .listen('{$modelName}.updated', (d: unknown) => onEvent('updated', d))
    .listen('{$modelName}.deleted', (d: unknown) => onEvent('deleted', d));

  return () => window.Echo.leave('{$route}');
}
TS;
    }
}
