<?php

namespace Julio\Capyrel\Generators;

use Illuminate\Support\Str;
use Julio\Capyrel\Detectors\UploadColumnDetector;

/**
 * Generates a Lighthouse PHP GraphQL schema for all detected models.
 *
 * Output: graphql/schema.graphql (appended per model)
 *
 * Generates:
 *  - Type definitions with all fields
 *  - Query: single + paginated list with filters
 *  - Mutation: create, update, delete, bulkDelete
 *  - Input types for create/update
 *  - ENUM types for ENUM columns
 *  - Relationship fields with @belongsTo, @hasMany, @belongsToMany
 *
 * Requires: nuwave/lighthouse
 */
class GraphQLGenerator
{
    private array $skip = [
        'remember_token', 'two_factor_secret', 'two_factor_recovery_codes', 'password',
    ];

    public function generateSchema(array $models): string
    {
        $sections = [
            '# Auto-generated by Capyrel. Requires: nuwave/lighthouse',
            '# Do not edit — re-generate with: php artisan capyrel:graphql',
            '',
        ];

        foreach ($models as $modelName => ['columns' => $columns, 'relationships' => $rels]) {
            $sections[] = $this->generateModelSection($modelName, $columns, $rels);
        }

        // Root Query + Mutation types
        $sections[] = $this->generateRootTypes($models);

        return implode("\n\n", array_filter($sections));
    }

    public function generateModelSection(string $modelName, array $columns, array $relationships): string
    {
        $type        = $this->buildType($modelName, $columns, $relationships);
        $enums       = $this->buildEnumTypes($columns, $modelName);
        $createInput = $this->buildInputType($modelName, $columns, 'Create');
        $updateInput = $this->buildInputType($modelName, $columns, 'Update');

        return implode("\n\n", array_filter([$enums, $type, $createInput, $updateInput]));
    }

    // ── Type builder ──────────────────────────────────────────────────────────

    private function buildType(string $modelName, array $columns, array $relationships): string
    {
        $fields = $this->typeFields($columns, $relationships);

        return <<<GQL
type {$modelName} {
{$fields}
}
GQL;
    }

    private function typeFields(array $columns, array $relationships): string
    {
        $lines = ['    id: ID! @eq'];

        foreach ($columns as $col) {
            $name = $col['name'];
            if (in_array($name, $this->skip) || $name === 'id') continue;

            $gqlType  = $this->gqlType($col);
            $nullable = (bool) ($col['nullable'] ?? false);
            $bang     = $nullable ? '' : '!';
            $directives = $this->fieldDirectives($col);

            if (UploadColumnDetector::isUploadColumn($name)) {
                $lines[] = "    {$name}: String{$bang}          # Stored file path";
                $lines[] = "    {$name}_url: String         # Full URL via model accessor";
                continue;
            }

            $lines[] = "    {$name}: {$gqlType}{$bang}{$directives}";
        }

        // Relationships
        foreach ($relationships as $rel) {
            if (empty($rel['related']) || $rel['type'] === 'morphTo') continue;
            $method  = $rel['method'];
            $related = $rel['related'];

            $lines[] = match($rel['type']) {
                'hasMany', 'hasManyThrough'         => "    {$method}: [{$related}!]! @hasMany",
                'belongsToMany', 'morphToMany'      => "    {$method}: [{$related}!]! @belongsToMany",
                'hasOne', 'hasOneThrough'            => "    {$method}: {$related} @hasOne",
                'belongsTo'                          => "    {$method}: {$related} @belongsTo",
                'morphMany'                          => "    {$method}: [{$related}!]! @morphMany",
                default                              => "    {$method}: {$related}",
            };

            if (in_array($rel['type'], ['hasMany','belongsToMany','morphMany'])) {
                $lines[] = "    {$method}_count: Int @withCount";
            }
        }

        return implode("\n", $lines);
    }

    // ── Input types ───────────────────────────────────────────────────────────

    private function buildInputType(string $modelName, array $columns, string $prefix): string
    {
        $skip    = ['id','created_at','updated_at','deleted_at','remember_token','email_verified_at'];
        $lines   = [];
        $isUpdate = $prefix === 'Update';

        if ($isUpdate) {
            $lines[] = '    id: ID!';
        }

        foreach ($columns as $col) {
            $name     = $col['name'];
            $nullable = (bool) ($col['nullable'] ?? false);
            if (in_array($name, $skip)) continue;
            if (in_array($name, $this->skip)) continue;

            if (UploadColumnDetector::isUploadColumn($name)) {
                $lines[] = "    {$name}: Upload" . ($isUpdate ? '' : ($nullable ? '' : '!'));
                continue;
            }

            $gqlType  = $this->gqlType($col);
            $required = !$nullable && !$isUpdate ? '!' : '';
            $lines[]  = "    {$name}: {$gqlType}{$required}";
        }

        $inputName = "{$prefix}{$modelName}Input";
        $fields    = implode("\n", $lines);

        return <<<GQL
input {$inputName} {
{$fields}
}
GQL;
    }

    // ── Enum types ────────────────────────────────────────────────────────────

    private function buildEnumTypes(array $columns, string $modelName): string
    {
        $types = [];

        foreach ($columns as $col) {
            if (strtolower($col['type_name'] ?? '') !== 'enum') continue;
            preg_match_all("/'([^']+)'/", $col['type'] ?? '', $m);
            if (empty($m[1])) continue;

            $enumName = $modelName . Str::studly($col['name']);
            $values   = implode("\n", array_map(fn($v) => '    ' . strtoupper($v), $m[1]));
            $types[]  = "enum {$enumName} {\n{$values}\n}";
        }

        return implode("\n\n", $types);
    }

    // ── Root Query + Mutation ─────────────────────────────────────────────────

    private function generateRootTypes(array $models): string
    {
        $queryFields    = [];
        $mutationFields = [];

        foreach ($models as $modelName => ['columns' => $columns, 'relationships' => $rels]) {
            $singular  = Str::camel($modelName);
            $plural    = Str::camel(Str::plural($modelName));
            $hasSoft   = in_array('deleted_at', array_column($columns, 'name'));
            $trashed   = $hasSoft ? "\n        trashed: Trashed @trashed" : '';

            $queryFields[] = <<<GQL
    {$singular}(id: ID! @eq): {$modelName} @find @guard
    {$plural}(
        search: String @search
        orderBy: [{$modelName}OrderByInput]
        {$trashed}
    ): [{$modelName}!]! @paginate(defaultCount: 15) @guard @can(ability: "viewAny", model: "App\\\\Models\\\\{$modelName}")
GQL;

            $mutationFields[] = <<<GQL
    create{$modelName}(input: Create{$modelName}Input! @spread): {$modelName}! @create @guard @can(ability: "create", model: "App\\\\Models\\\\{$modelName}")
    update{$modelName}(input: Update{$modelName}Input! @spread): {$modelName}! @update @guard @can(ability: "update", find: "id")
    delete{$modelName}(id: ID!): {$modelName} @delete @guard @can(ability: "delete", find: "id")
GQL;
        }

        $queries   = implode("\n\n", $queryFields);
        $mutations = implode("\n\n", $mutationFields);

        return <<<GQL
type Query {
{$queries}
}

type Mutation {
{$mutations}
}

input OrderDirection {
    field: String!
    order: SortOrder!
}

enum SortOrder {
    ASC
    DESC
}

enum Trashed {
    ONLY
    WITH
    WITHOUT
}
GQL;
    }

    // ── Type mapping ──────────────────────────────────────────────────────────

    private function gqlType(array $col): string
    {
        $type = strtolower($col['type_name'] ?? 'string');
        $name = $col['name'];

        if (str_ends_with($name, '_id')) return 'ID';

        if (strtolower($col['type_name'] ?? '') === 'enum') {
            // Reference the generated enum type
            return 'String'; // Could be specific enum type
        }

        return match(true) {
            in_array($type, ['int','integer','bigint','smallint','tinyint','mediumint']) => 'Int',
            in_array($type, ['decimal','float','double','numeric','real'])              => 'Float',
            in_array($type, ['boolean','bool'])                                         => 'Boolean',
            in_array($type, ['json','jsonb'])                                           => 'JSON',
            in_array($type, ['date','datetime','timestamp','datetimetz'])               => 'DateTime',
            default                                                                     => 'String',
        };
    }

    private function fieldDirectives(array $col): string
    {
        $name = $col['name'];
        $directives = '';

        if (str_ends_with($name, '_at') || in_array(strtolower($col['type_name'] ?? ''), ['datetime','timestamp'])) {
            // DateTime scalar handled by Lighthouse
        }

        return $directives ? ' ' . $directives : '';
    }
}
