<?php

namespace Julio\Capyrel\Generators;

use Illuminate\Support\Str;
use Julio\Capyrel\Detectors\UploadColumnDetector;

/**
 * Generates a complete OpenAPI 3.1 YAML specification from the schema.
 * Derives:
 *   - Component schemas from column types and ENUM values
 *   - Request bodies from validation rules
 *   - Responses from resource structures
 *   - Parameters from filter/sort/search blocks
 *   - Tags from model names
 *
 * Output: storage/app/openapi.yaml  (also serveable at /api/docs)
 */
class OpenApiGenerator
{
    private string $indent = '  ';

    public function generate(string $appName, string $appUrl, array $models): string
    {
        $schemas    = $this->buildSchemas($models);
        $paths      = $this->buildPaths($models);
        $tags       = $this->buildTags($models);

        return <<<YAML
openapi: "3.1.0"

info:
  title: "{$appName} API"
  description: "Auto-generated by Capyrel from database schema."
  version: "1.0.0"

servers:
  - url: "{$appUrl}/api"
    description: "Application API"

tags:
{$tags}

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
{$schemas}

paths:
{$paths}
YAML;
    }

    public function generateForModel(
        string $modelName,
        array  $columns,
        array  $relationships,
        array  $enumCols = []
    ): array {
        return [
            'schema'        => $this->modelSchema($modelName, $columns, $relationships),
            'createSchema'  => $this->createSchema($modelName, $columns),
            'updateSchema'  => $this->updateSchema($modelName, $columns),
            'paths'         => $this->modelPaths($modelName, $columns, $enumCols),
        ];
    }

    // ── Schemas ───────────────────────────────────────────────────────────────

    private function buildSchemas(array $models): string
    {
        $sections = [];

        foreach ($models as $modelName => ['columns' => $columns, 'relationships' => $rels]) {
            $sections[] = $this->modelSchema($modelName, $columns, $rels);
            $sections[] = $this->createSchema($modelName, $columns);
            $sections[] = $this->updateSchema($modelName, $columns);
        }

        return implode("\n", $sections);
    }

    private function modelSchema(string $modelName, array $columns, array $relationships): string
    {
        $props   = $this->buildSchemaProperties($columns, $relationships, 'response');
        $required = $this->buildRequiredList($columns, 'response');

        return <<<YAML
    {$modelName}:
      type: object
      required: [{$required}]
      properties:
{$props}
YAML;
    }

    private function createSchema(string $modelName, array $columns): string
    {
        $props    = $this->buildSchemaProperties($columns, [], 'create');
        $required = $this->buildRequiredList($columns, 'create');
        $enctype  = !empty(UploadColumnDetector::collectFrom($columns)) ? "\n      encoding: {}" : '';

        return <<<YAML
    Create{$modelName}:
      type: object
      required: [{$required}]
      properties:
{$props}{$enctype}
YAML;
    }

    private function updateSchema(string $modelName, array $columns): string
    {
        $props = $this->buildSchemaProperties($columns, [], 'update');

        return <<<YAML
    Update{$modelName}:
      type: object
      properties:
{$props}
YAML;
    }

    private function buildSchemaProperties(array $columns, array $relationships, string $mode): string
    {
        $skip  = ['remember_token', 'two_factor_secret', 'two_factor_recovery_codes', 'password'];
        $writeskip = ['id', 'created_at', 'updated_at', 'deleted_at', 'remember_token', 'email_verified_at'];
        $lines = [];

        if ($mode === 'response') {
            $lines[] = "        id:\n          type: integer\n          readOnly: true";
        }

        foreach ($columns as $col) {
            $name = $col['name'];
            if (in_array($name, $skip)) continue;
            if (in_array($mode, ['create','update']) && in_array($name, $writeskip)) continue;

            $type   = strtolower($col['type_name'] ?? 'string');
            $nullable = (bool) ($col['nullable'] ?? false);

            if (UploadColumnDetector::isUploadColumn($name)) {
                $lines[] = "        {$name}:\n          type: string\n          format: binary";
                continue;
            }

            $yamlType = $this->yamlType($type);
            $format   = $this->yamlFormat($type, $name);
            $enumVals = $type === 'enum' ? $this->parseEnumValues($col['type'] ?? '') : [];

            $prop = "        {$name}:\n          type: {$yamlType}";
            if ($format) $prop .= "\n          format: {$format}";
            if ($nullable) $prop .= "\n          nullable: true";
            if (!empty($enumVals)) {
                $prop .= "\n          enum: [" . implode(', ', array_map(fn($v) => "\"{$v}\"", $enumVals)) . "]";
            }
            if ($mode === 'response' && str_ends_with($name, '_at')) {
                $prop .= "\n          readOnly: true";
            }
            $lines[] = $prop;
        }

        // Response: append _url accessors for file columns
        if ($mode === 'response') {
            foreach (UploadColumnDetector::collectFrom($columns) as $col) {
                $lines[] = "        {$col}_url:\n          type: string\n          format: uri\n          nullable: true\n          readOnly: true";
            }
        }

        // Response: relationship refs
        if ($mode === 'response') {
            foreach ($relationships as $rel) {
                if (empty($rel['related']) || $rel['type'] === 'morphTo') continue;
                $method  = $rel['method'];
                $related = $rel['related'];
                if (in_array($rel['type'], ['hasMany','belongsToMany','hasManyThrough'])) {
                    $lines[] = "        {$method}:\n          type: array\n          items:\n            \$ref: '#/components/schemas/{$related}'\n          readOnly: true";
                    $lines[] = "        {$method}_count:\n          type: integer\n          readOnly: true";
                } else {
                    $lines[] = "        {$method}:\n          \$ref: '#/components/schemas/{$related}'\n          readOnly: true";
                }
            }
            $lines[] = "        created_at:\n          type: string\n          format: date-time\n          readOnly: true";
            $lines[] = "        updated_at:\n          type: string\n          format: date-time\n          readOnly: true";
        }

        return implode("\n", $lines);
    }

    private function buildRequiredList(array $columns, string $mode): string
    {
        $skip  = ['id','created_at','updated_at','deleted_at','remember_token','email_verified_at'];
        if ($mode === 'response') return 'id';

        $required = [];
        foreach ($columns as $col) {
            if (in_array($col['name'], $skip)) continue;
            if (!($col['nullable'] ?? false) && !UploadColumnDetector::isUploadColumn($col['name'])) {
                $required[] = $col['name'];
            }
        }
        return implode(', ', $required);
    }

    // ── Paths ─────────────────────────────────────────────────────────────────

    private function buildPaths(array $models): string
    {
        $sections = [];

        foreach ($models as $modelName => ['columns' => $columns, 'relationships' => $rels]) {
            $enumCols = array_filter($columns, fn($c) => strtolower($c['type_name'] ?? '') === 'enum');
            $sections[] = $this->modelPaths($modelName, $columns, array_values($enumCols));
        }

        return implode("\n", $sections);
    }

    private function modelPaths(string $modelName, array $columns, array $enumCols): string
    {
        $route    = Str::kebab(Str::plural($modelName));
        $variable = Str::camel($modelName);
        $tag      = Str::headline(Str::plural($modelName));

        $searchCols  = array_slice(array_column(
            array_filter($columns, fn($c) => in_array(strtolower($c['type_name'] ?? ''), ['varchar','text','char'])),
            'name'
        ), 0, 3);

        $filterParams = $this->buildFilterParams($columns, $enumCols);
        $sortParam    = $this->buildSortParam($columns);

        return <<<YAML
  /api/{$route}:
    get:
      tags: ["{$tag}"]
      summary: "List {$tag}"
      operationId: "{$variable}.index"
      parameters:
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: per_page
          in: query
          schema: { type: integer, default: 15, maximum: 100 }
        - name: search
          in: query
          description: "Full-text search across string columns"
          schema: { type: string }
        - name: include
          in: query
          description: "Comma-separated relationships to include"
          schema: { type: string }
        - name: trashed
          in: query
          schema: { type: string, enum: [only, with] }
{$filterParams}{$sortParam}
      responses:
        "200":
          description: "Paginated list of {$modelName}"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      \$ref: "#/components/schemas/{$modelName}"
                  meta:
                    type: object
                  links:
                    type: object
        "401": { description: "Unauthenticated" }
        "403": { description: "Unauthorized" }

    post:
      tags: ["{$tag}"]
      summary: "Create {$modelName}"
      operationId: "{$variable}.store"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              \$ref: "#/components/schemas/Create{$modelName}"
          application/json:
            schema:
              \$ref: "#/components/schemas/Create{$modelName}"
      responses:
        "201":
          description: "{$modelName} created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  data:
                    \$ref: "#/components/schemas/{$modelName}"
        "422": { description: "Validation error" }
        "401": { description: "Unauthenticated" }
        "403": { description: "Unauthorized" }

  /api/{$route}/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: integer }

    get:
      tags: ["{$tag}"]
      summary: "Get {$modelName}"
      operationId: "{$variable}.show"
      parameters:
        - name: include
          in: query
          schema: { type: string }
      responses:
        "200":
          description: "{$modelName} resource"
          content:
            application/json:
              schema:
                \$ref: "#/components/schemas/{$modelName}"
        "404": { description: "Not found" }
        "401": { description: "Unauthenticated" }

    put:
      tags: ["{$tag}"]
      summary: "Update {$modelName}"
      operationId: "{$variable}.update"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              \$ref: "#/components/schemas/Update{$modelName}"
          application/json:
            schema:
              \$ref: "#/components/schemas/Update{$modelName}"
      responses:
        "200":
          description: "{$modelName} updated"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  data:
                    \$ref: "#/components/schemas/{$modelName}"
        "422": { description: "Validation error" }
        "404": { description: "Not found" }

    delete:
      tags: ["{$tag}"]
      summary: "Delete {$modelName}"
      operationId: "{$variable}.destroy"
      responses:
        "200":
          description: "{$modelName} deleted"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
        "404": { description: "Not found" }

  /api/{$route}/bulk-destroy:
    post:
      tags: ["{$tag}"]
      summary: "Bulk delete {$tag}"
      operationId: "{$variable}.bulkDestroy"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ids]
              properties:
                ids:
                  type: array
                  items: { type: integer }
                  minItems: 1
                  maxItems: 100
      responses:
        "200":
          description: "Records deleted"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }

YAML;
    }

    private function buildFilterParams(array $columns, array $enumCols): string
    {
        $lines = [];

        foreach ($enumCols as $col) {
            $vals  = $this->parseEnumValues($col['type'] ?? '');
            $enum  = implode(', ', array_map(fn($v) => "\"{$v}\"", $vals));
            $lines[] = "        - name: {$col['name']}\n          in: query\n          schema: { type: string, enum: [{$enum}] }";
        }

        // Numeric range filters
        foreach ($columns as $col) {
            $type = strtolower($col['type_name'] ?? '');
            if (!in_array($type, ['decimal','float','double','int','integer','bigint'])) continue;
            $name = $col['name'];
            if (in_array($name, ['id','created_at','updated_at'])) continue;
            $lines[] = "        - name: {$name}_min\n          in: query\n          schema: { type: number }";
            $lines[] = "        - name: {$name}_max\n          in: query\n          schema: { type: number }";
        }

        return $lines ? implode("\n", $lines) . "\n" : '';
    }

    private function buildSortParam(array $columns): string
    {
        $sortable = array_filter(array_column($columns, 'name'), fn($n) =>
            !in_array($n, ['password','remember_token','two_factor_secret'])
        );
        $enum = implode(', ', array_map(fn($v) => "\"{$v}\"", array_slice(array_values($sortable), 0, 10)));

        return <<<YAML
        - name: sort
          in: query
          schema: { type: string, enum: [{$enum}] }
        - name: direction
          in: query
          schema: { type: string, enum: [asc, desc], default: desc }
YAML;
    }

    private function buildTags(array $models): string
    {
        $lines = [];
        foreach (array_keys($models) as $modelName) {
            $tag   = Str::headline(Str::plural($modelName));
            $lines[] = "  - name: \"{$tag}\"\n    description: \"Operations for {$modelName} resources\"";
        }
        return implode("\n", $lines);
    }

    // ── Type mapping ──────────────────────────────────────────────────────────

    private function yamlType(string $type): string
    {
        return match(true) {
            in_array($type, ['int','integer','bigint','smallint','tinyint','mediumint']) => 'integer',
            in_array($type, ['decimal','float','double','numeric','real'])              => 'number',
            in_array($type, ['boolean','bool'])                                         => 'boolean',
            in_array($type, ['json','jsonb'])                                           => 'object',
            default                                                                     => 'string',
        };
    }

    private function yamlFormat(string $type, string $name): string
    {
        if (str_contains($name, 'email')) return 'email';
        if (str_contains($name, 'url') || $name === 'website') return 'uri';
        if (in_array($type, ['datetime','timestamp','datetimetz'])) return 'date-time';
        if ($type === 'date') return 'date';
        if ($type === 'uuid') return 'uuid';
        if (in_array($type, ['bigint','int','integer'])) return 'int64';
        return '';
    }

    private function parseEnumValues(string $typeStr): array
    {
        if (!str_starts_with(strtolower($typeStr), 'enum(')) return [];
        preg_match_all("/'([^']+)'/", $typeStr, $m);
        return $m[1] ?? [];
    }
}
