<?php

namespace Julio\Capyrel\Generators;

use Illuminate\Support\Str;

/**
 * Generates the complete permission/authorization layer:
 *
 *   1. Permission matrix seeder — every action for every model
 *   2. Policy class per model — with per-method gate abilities
 *   3. Role seeder — admin, editor, viewer with sensible defaults
 *
 * Requires spatie/laravel-permission (auto-detected).
 * Works without Spatie using standard Laravel Policies too.
 */
class PermissionMatrixGenerator
{
    private array $defaultAbilities = [
        'viewAny', 'view', 'create', 'update', 'delete',
        'deleteAny', 'restore', 'forceDelete', 'export', 'import',
    ];

    public function generatePolicy(string $modelName, array $columns): string
    {
        $variable  = Str::camel($modelName);
        $hasSoft   = in_array('deleted_at', array_column($columns, 'name'));
        $softMethods = $hasSoft ? $this->buildSoftPolicyMethods($modelName, $variable) : '';

        return <<<PHP
<?php

namespace App\Policies;

use App\Models\\{$modelName};
use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class {$modelName}Policy
{
    use HandlesAuthorization;

    /** Admins bypass all checks. */
    public function before(User \$user, string \$ability): ?bool
    {
        if (method_exists(\$user, 'hasRole') && \$user->hasRole('admin')) {
            return true;
        }
        return null;
    }

    /** Can list all {$modelName} records. */
    public function viewAny(User \$user): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'viewAny')}');
    }

    /** Can view a single {$modelName}. */
    public function view(User \$user, {$modelName} \${$variable}): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'view')}');
    }

    /** Can create a {$modelName}. */
    public function create(User \$user): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'create')}');
    }

    /** Can update a {$modelName}. */
    public function update(User \$user, {$modelName} \${$variable}): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'update')}');
    }

    /** Can delete a {$modelName}. */
    public function delete(User \$user, {$modelName} \${$variable}): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'delete')}');
    }

    /** Can bulk-delete multiple {$modelName} records. */
    public function deleteAny(User \$user): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'deleteAny')}');
    }

    /** Can export {$modelName} data. */
    public function export(User \$user): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'export')}');
    }
{$softMethods}
    // ── Helper ────────────────────────────────────────────────────────────────

    private function hasPermission(User \$user, string \$permission): bool
    {
        // Spatie: uses hasPermissionTo()
        if (method_exists(\$user, 'hasPermissionTo')) {
            return \$user->hasPermissionTo(\$permission);
        }
        // Standard Laravel gate
        return \$user->can(\$permission);
    }
}
PHP;
    }

    public function generatePermissionSeeder(array $modelNames): string
    {
        $lines = [];

        foreach ($modelNames as $modelName) {
            $lines[] = "        // {$modelName} permissions";
            foreach ($this->defaultAbilities as $ability) {
                $perm = $this->permName($modelName, $ability);
                $lines[] = "        Permission::firstOrCreate(['name' => '{$perm}', 'guard_name' => 'web']);";
            }
            $lines[] = '';
        }

        $permBlock = implode("\n", $lines);

        return <<<PHP
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

/**
 * Auto-generated by Capyrel.
 * Seeds all model permissions and assigns them to default roles.
 *
 * Roles:
 *   admin  — full access to everything
 *   editor — create/read/update, no delete
 *   viewer — read-only
 */
class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // ── Permissions ───────────────────────────────────────────────────────

{$permBlock}

        // ── Roles ─────────────────────────────────────────────────────────────

        \$admin  = Role::firstOrCreate(['name' => 'admin',  'guard_name' => 'web']);
        \$editor = Role::firstOrCreate(['name' => 'editor', 'guard_name' => 'web']);
        \$viewer = Role::firstOrCreate(['name' => 'viewer', 'guard_name' => 'web']);

        // Admin gets everything
        \$admin->syncPermissions(Permission::all());

        // Editor can CRUD but not delete permanently, not export/import
        \$editorPerms = Permission::whereNotIn('name', \$this->buildExcluded([
            'deleteAny', 'forceDelete', 'import',
        ]))->pluck('name');
        \$editor->syncPermissions(\$editorPerms);

        // Viewer can only read
        \$viewerPerms = Permission::where('name', 'like', '%.viewAny')
            ->orWhere('name', 'like', '%.view')
            ->orWhere('name', 'like', '%.export')
            ->pluck('name');
        \$viewer->syncPermissions(\$viewerPerms);
    }

    private function buildExcluded(array \$abilities): array
    {
        return array_map(fn(\$a) => '%.' . \$a, \$abilities);
    }
}
PHP;
    }

    public function generatePolicyServiceProviderRegistration(array $modelNames): string
    {
        $lines = [];
        foreach ($modelNames as $modelName) {
            $lines[] = "        Gate::policy(\\App\\Models\\{$modelName}::class, \\App\\Policies\\{$modelName}Policy::class);";
        }

        $registrations = implode("\n", $lines);

        return <<<PHP
<?php
// Add the following to App\Providers\AppServiceProvider::boot():

{$registrations}
PHP;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function permName(string $modelName, string $ability): string
    {
        return Str::snake(Str::plural($modelName)) . '.' . Str::snake($ability);
    }

    private function buildSoftPolicyMethods(string $modelName, string $variable): string
    {
        return <<<PHP

    /** Can restore a soft-deleted {$modelName}. */
    public function restore(User \$user, {$modelName} \${$variable}): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'restore')}');
    }

    /** Can permanently delete a {$modelName}. */
    public function forceDelete(User \$user, {$modelName} \${$variable}): bool
    {
        return \$this->hasPermission(\$user, '{$this->permName($modelName, 'forceDelete')}');
    }

PHP;
    }
}
