<?php

namespace Julio\Capyrel\Generators;

use Illuminate\Support\Str;
use Julio\Capyrel\Detectors\UploadColumnDetector;

/**
 * Generates a Postman Collection v2.1 JSON for all model endpoints.
 * Import into Postman or Insomnia with one click.
 *
 * Features:
 *  - Pre-request script injects Bearer token from {{token}} variable
 *  - Request body uses realistic example values from column types
 *  - Query parameters documented with descriptions
 *  - Separate folders per model
 *  - Environment variable: {{base_url}}
 */
class PostmanGenerator
{
    public function generate(string $appName, string $baseUrl, array $models): string
    {
        $items = [];

        foreach ($models as $modelName => ['columns' => $columns, 'relationships' => $rels]) {
            $items[] = $this->modelFolder($modelName, $columns, $rels);
        }

        $collection = [
            'info' => [
                '_postman_id' => $this->uuid(),
                'name'        => $appName . ' API',
                'description' => 'Auto-generated by Capyrel from database schema.',
                'schema'      => 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
            ],
            'auth' => [
                'type'   => 'bearer',
                'bearer' => [['key' => 'token', 'value' => '{{token}}', 'type' => 'string']],
            ],
            'variable' => [
                ['key' => 'base_url', 'value' => $baseUrl,   'type' => 'string'],
                ['key' => 'token',    'value' => '',          'type' => 'string'],
            ],
            'item' => $items,
        ];

        return json_encode($collection, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function modelFolder(string $modelName, array $columns, array $relationships): array
    {
        $route   = Str::kebab(Str::plural($modelName));
        $title   = Str::headline(Str::plural($modelName));
        $hasFiles = !empty(UploadColumnDetector::collectFrom($columns));
        $hasSoft  = in_array('deleted_at', array_column($columns, 'name'));

        $requests = [
            $this->indexRequest($modelName, $route, $columns),
            $this->storeRequest($modelName, $route, $columns, $relationships, $hasFiles),
            $this->showRequest($modelName, $route),
            $this->updateRequest($modelName, $route, $columns, $relationships, $hasFiles),
            $this->destroyRequest($modelName, $route),
            $this->bulkDestroyRequest($modelName, $route),
        ];

        if ($hasSoft) {
            $requests[] = $this->restoreRequest($modelName, $route);
            $requests[] = $this->forceDeleteRequest($modelName, $route);
        }

        return [
            'name' => $title,
            'item' => $requests,
        ];
    }

    // ── Request builders ──────────────────────────────────────────────────────

    private function indexRequest(string $modelName, string $route, array $columns): array
    {
        $sortCols = implode(',', array_slice(array_column($columns, 'name'), 0, 5));

        return $this->request("List {$modelName}s", 'GET', "{{base_url}}/{$route}", [
            ['key' => 'page',      'value' => '1',   'description' => 'Page number'],
            ['key' => 'per_page',  'value' => '15',  'description' => 'Items per page (max 100)'],
            ['key' => 'search',    'value' => '',    'description' => 'Full-text search', 'disabled' => true],
            ['key' => 'sort',      'value' => 'created_at', 'description' => "Sort column: {$sortCols}"],
            ['key' => 'direction', 'value' => 'desc','description' => 'asc or desc'],
            ['key' => 'include',   'value' => '',    'description' => 'Comma-separated relations', 'disabled' => true],
            ['key' => 'trashed',   'value' => '',    'description' => 'only|with (soft-deletes)', 'disabled' => true],
        ]);
    }

    private function storeRequest(string $m, string $route, array $columns, array $rels, bool $hasFiles): array
    {
        $bodyMode = $hasFiles ? 'formdata' : 'raw';
        $body     = $hasFiles
            ? $this->formDataBody($columns, $rels)
            : $this->jsonBody($columns, $rels);

        return $this->request("Create {$m}", 'POST', "{{base_url}}/{$route}", [], $bodyMode, $body);
    }

    private function showRequest(string $m, string $route): array
    {
        return $this->request("Show {$m}", 'GET', "{{base_url}}/{$route}/{{id}}", [
            ['key' => 'include', 'value' => '', 'description' => 'Comma-separated relations', 'disabled' => true],
        ]);
    }

    private function updateRequest(string $m, string $route, array $columns, array $rels, bool $hasFiles): array
    {
        $bodyMode = $hasFiles ? 'formdata' : 'raw';
        $body     = $hasFiles
            ? array_merge([['key' => '_method', 'value' => 'PUT', 'type' => 'text']], $this->formDataBody($columns, $rels))
            : $this->jsonBody($columns, $rels);

        return $this->request("Update {$m}", 'POST', "{{base_url}}/{$route}/{{id}}", [], $bodyMode, $body);
    }

    private function destroyRequest(string $m, string $route): array
    {
        return $this->request("Delete {$m}", 'DELETE', "{{base_url}}/{$route}/{{id}}");
    }

    private function bulkDestroyRequest(string $m, string $route): array
    {
        return $this->request(
            "Bulk Delete {$m}s", 'POST', "{{base_url}}/{$route}/bulk-destroy",
            [], 'raw',
            json_encode(['ids' => [1, 2, 3]], JSON_PRETTY_PRINT)
        );
    }

    private function restoreRequest(string $m, string $route): array
    {
        return $this->request("Restore {$m}", 'POST', "{{base_url}}/{$route}/{{id}}/restore");
    }

    private function forceDeleteRequest(string $m, string $route): array
    {
        return $this->request("Force Delete {$m}", 'DELETE', "{{base_url}}/{$route}/{{id}}/force");
    }

    // ── Body builders ─────────────────────────────────────────────────────────

    private function formDataBody(array $columns, array $rels): array
    {
        $skip  = ['id','created_at','updated_at','deleted_at','remember_token','email_verified_at'];
        $items = [];

        foreach ($columns as $col) {
            $name = $col['name'];
            if (in_array($name, $skip)) continue;

            if (UploadColumnDetector::isUploadColumn($name)) {
                $items[] = ['key' => $name, 'type' => 'file', 'src' => '', 'disabled' => true];
                continue;
            }

            $items[] = [
                'key'   => $name,
                'value' => $this->exampleValue($col),
                'type'  => 'text',
            ];
        }

        foreach ($rels as $rel) {
            if ($rel['type'] !== 'belongsToMany') continue;
            $items[] = ['key' => "{$rel['method']}_ids[]", 'value' => '1', 'type' => 'text'];
        }

        return $items;
    }

    private function jsonBody(array $columns, array $rels): string
    {
        $skip  = ['id','created_at','updated_at','deleted_at','remember_token','email_verified_at'];
        $body  = [];

        foreach ($columns as $col) {
            $name = $col['name'];
            if (in_array($name, $skip)) continue;
            if (UploadColumnDetector::isUploadColumn($name)) continue;
            $body[$name] = $this->exampleValue($col);
        }

        foreach ($rels as $rel) {
            if ($rel['type'] === 'belongsToMany') {
                $body["{$rel['method']}_ids"] = [1, 2];
            }
        }

        return json_encode($body, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function exampleValue(array $col): mixed
    {
        $name = $col['name'];
        $type = strtolower($col['type_name'] ?? 'string');

        if (str_contains($name, 'email')) return 'user@example.com';
        if ($name === 'password') return 'SecretPass1!';
        if ($name === 'title') return 'Example Title';
        if ($name === 'name') return 'Example Name';
        if ($name === 'slug') return 'example-slug';
        if (str_contains($name, 'url') || $name === 'website') return 'https://example.com';
        if (str_ends_with($name, '_id')) return 1;
        if ($type === 'enum') {
            preg_match_all("/'([^']+)'/", $col['type'] ?? '', $m);
            return $m[1][0] ?? 'value';
        }

        return match(true) {
            in_array($type, ['int','integer','bigint','smallint']) => 1,
            in_array($type, ['decimal','float','double','numeric']) => '9.99',
            in_array($type, ['boolean','bool','tinyint']) => true,
            in_array($type, ['date']) => date('Y-m-d'),
            in_array($type, ['datetime','timestamp']) => date('Y-m-d H:i:s'),
            in_array($type, ['json','jsonb']) => '{}',
            default => 'Example value',
        };
    }

    // ── Low-level builder ─────────────────────────────────────────────────────

    private function request(string $name, string $method, string $url, array $query = [], string $bodyMode = 'raw', mixed $body = null): array
    {
        $r = [
            'name' => $name,
            'request' => [
                'method' => $method,
                'header' => [
                    ['key' => 'Accept', 'value' => 'application/json'],
                    ['key' => 'Content-Type', 'value' => $bodyMode === 'raw' ? 'application/json' : 'multipart/form-data'],
                ],
                'url' => [
                    'raw'   => $url,
                    'host'  => ['{{base_url}}'],
                    'path'  => explode('/', ltrim(str_replace('{{base_url}}', '', $url), '/')),
                    'query' => array_map(fn($q) => array_merge(['disabled' => false], $q), $query),
                ],
            ],
        ];

        if ($body !== null) {
            if ($bodyMode === 'formdata') {
                $r['request']['body'] = ['mode' => 'formdata', 'formdata' => $body];
            } else {
                $r['request']['body'] = ['mode' => 'raw', 'raw' => $body, 'options' => ['raw' => ['language' => 'json']]];
            }
        }

        return $r;
    }

    private function uuid(): string
    {
        return sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff),
            mt_rand(0, 0x0fff) | 0x4000, mt_rand(0, 0x3fff) | 0x8000,
            mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
        );
    }
}
