<?php

namespace Julio\Capyrel\Generators;

use Illuminate\Support\Str;
use Julio\Capyrel\Detectors\UploadColumnDetector;

/**
 * Generates TypeScript interfaces and payload types.
 *
 * Output per model:
 *   resources/ts/models/{Model}.ts        — response interface
 *   resources/ts/models/index.ts          — barrel re-export
 */
class TypeScriptGenerator
{
    private array $skip = [
        'password', 'remember_token', 'two_factor_secret', 'two_factor_recovery_codes',
    ];

    public function generateInterface(string $modelName, array $columns, array $relationships): string
    {
        $props       = $this->buildResponseProps($columns, $relationships);
        $createProps = $this->buildCreateProps($columns, $relationships);
        $updateProps = $this->buildUpdateProps($columns);
        $enumTypes   = $this->buildEnumTypes($columns, $modelName);
        $relImports  = $this->buildRelImports($relationships, $modelName);

        return <<<TS
// Auto-generated by Capyrel. Do not edit manually.
// Re-generate with: php artisan capyrel:typescript
{$relImports}
{$enumTypes}
/** Full {$modelName} object as returned by the API. */
export interface {$modelName} {
{$props}
}

/** Fields sent when creating a new {$modelName}. */
export interface Create{$modelName}Payload {
{$createProps}
}

/** Fields sent when updating an existing {$modelName} (all optional). */
export interface Update{$modelName}Payload {
{$updateProps}
}

/** Paginated API response wrapping a list of {$modelName}. */
export interface Paginated{$modelName} {
  data: {$modelName}[];
  meta: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
  links: {
    first: string | null;
    last: string | null;
    prev: string | null;
    next: string | null;
  };
}

/** Query parameters accepted by the index endpoint. */
export interface {$modelName}IndexParams {
  page?: number;
  per_page?: number;
  search?: string;
  sort?: string;
  direction?: 'asc' | 'desc';
  include?: string;
  trashed?: 'only' | 'with';
  [key: string]: string | number | undefined;
}
TS;
    }

    public function generateBarrel(array $modelNames): string
    {
        $exports = implode("\n", array_map(
            fn($m) => "export * from './{$m}';",
            $modelNames
        ));

        return <<<TS
// Auto-generated barrel export. Do not edit manually.
{$exports}
TS;
    }

    // ── Property builders ─────────────────────────────────────────────────────

    private function buildResponseProps(array $columns, array $relationships): string
    {
        $skip  = ['remember_token', 'two_factor_secret', 'two_factor_recovery_codes', 'password'];
        $lines = ['  id: number;'];

        foreach ($columns as $col) {
            $name     = $col['name'];
            $nullable = (bool) ($col['nullable'] ?? false);
            if (in_array($name, $skip) || $name === 'id') continue;

            $tsType = $this->tsType($col);

            if (UploadColumnDetector::isImageColumn($name)) {
                // Include the raw path AND the accessor URL
                $lines[] = "  {$name}: string | null;";
                $lines[] = "  {$name}_url: string | null;";
                continue;
            }

            $lines[] = "  {$name}: {$tsType}" . ($nullable ? ' | null' : '') . ';';
        }

        // File URL accessors (non-image uploads)
        foreach (UploadColumnDetector::collectFrom($columns) as $col) {
            if (!UploadColumnDetector::isImageColumn($col)) {
                $lines[] = "  {$col}_url: string | null;";
            }
        }

        // Timestamps
        $colNames = array_column($columns, 'name');
        if (in_array('created_at', $colNames)) $lines[] = "  created_at: string;";
        if (in_array('updated_at', $colNames)) $lines[] = "  updated_at: string;";
        if (in_array('deleted_at', $colNames)) $lines[] = "  deleted_at: string | null;";

        // Relationships
        foreach ($relationships as $rel) {
            if (empty($rel['related']) || $rel['type'] === 'morphTo') continue;
            $method  = $rel['method'];
            $related = $rel['related'];
            if (in_array($rel['type'], ['hasMany','belongsToMany','hasManyThrough'])) {
                $lines[] = "  {$method}?: {$related}[];";
                $lines[] = "  {$method}_count?: number;";
            } else {
                $lines[] = "  {$method}?: {$related} | null;";
            }
        }

        return implode("\n", $lines);
    }

    private function buildCreateProps(array $columns, array $relationships): string
    {
        $skip  = ['id','created_at','updated_at','deleted_at','remember_token','email_verified_at',
                  'two_factor_secret','two_factor_recovery_codes'];
        $lines = [];

        foreach ($columns as $col) {
            $name     = $col['name'];
            $nullable = (bool) ($col['nullable'] ?? false);
            if (in_array($name, $skip)) continue;

            if (UploadColumnDetector::isUploadColumn($name)) {
                $lines[] = "  {$name}?: File | null;";
                continue;
            }

            $tsType   = $this->tsType($col);
            $optional = $nullable ? '?' : '';
            $nullSuffix = $nullable ? ' | null' : '';
            $lines[]  = "  {$name}{$optional}: {$tsType}{$nullSuffix};";
        }

        // BTM pivot IDs
        foreach ($relationships as $rel) {
            if ($rel['type'] !== 'belongsToMany') continue;
            $lines[] = "  {$rel['method']}_ids?: number[];";
        }

        return implode("\n", $lines);
    }

    private function buildUpdateProps(array $columns): string
    {
        $lines = [];
        foreach ($columns as $col) {
            $name = $col['name'];
            $skip = ['id','created_at','updated_at','deleted_at','remember_token','email_verified_at'];
            if (in_array($name, $skip)) continue;

            if (UploadColumnDetector::isUploadColumn($name)) {
                $lines[] = "  {$name}?: File | null;";
                continue;
            }

            $tsType  = $this->tsType($col);
            $lines[] = "  {$name}?: {$tsType} | null;";
        }
        return implode("\n", $lines);
    }

    private function buildEnumTypes(array $columns, string $modelName): string
    {
        $types = [];
        foreach ($columns as $col) {
            if (strtolower($col['type_name'] ?? '') !== 'enum') continue;
            preg_match_all("/'([^']+)'/", $col['type'] ?? '', $m);
            if (empty($m[1])) continue;
            $typeName = $modelName . Str::studly($col['name']);
            $union    = implode(' | ', array_map(fn($v) => "'{$v}'", $m[1]));
            $types[]  = "export type {$typeName} = {$union};";
        }
        return $types ? implode("\n", $types) . "\n" : '';
    }

    private function buildRelImports(array $relationships, string $modelName): string
    {
        $models = collect($relationships)
            ->filter(fn($r) => !empty($r['related']) && $r['related'] !== $modelName && $r['type'] !== 'morphTo')
            ->pluck('related')->unique()->sort()->values();

        if ($models->isEmpty()) return '';

        return $models->map(fn($m) => "import type { {$m} } from './{$m}';")->implode("\n") . "\n";
    }

    // ── Type mapping ──────────────────────────────────────────────────────────

    private function tsType(array $col): string
    {
        $type = strtolower($col['type_name'] ?? 'string');
        $name = $col['name'];

        if (str_ends_with($name, '_id')) return 'number';
        if (strtolower($col['type_name'] ?? '') === 'enum') {
            // Reference the generated enum type
            return 'string'; // Could reference specific type, kept simple
        }

        return match(true) {
            in_array($type, ['int','integer','bigint','smallint','tinyint','mediumint']) => 'number',
            in_array($type, ['decimal','float','double','numeric','real'])              => 'number',
            in_array($type, ['boolean','bool'])                                         => 'boolean',
            in_array($type, ['json','jsonb'])                                           => 'Record<string, unknown>',
            in_array($type, ['date','datetime','timestamp','datetimetz'])               => 'string',
            default                                                                     => 'string',
        };
    }
}
