<?php

namespace Julio\Capyrel\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

class CleanCommand extends Command
{
    protected $signature = 'capyrel:clean
                            {--models      : Remove injected relationship methods from models only}
                            {--controllers : Remove generated controllers only}
                            {--views       : Remove generated blade directories only}
                            {--routes      : Remove generated routes from web.php only}
                            {--dry-run     : Show what would be removed without deleting}
                            {--force       : Skip all confirmations}';

    protected $description = 'Remove all code and files generated by capyrel';

    private int $modelsClean      = 0;
    private int $controllersClean = 0;
    private int $viewsClean       = 0;
    private bool $routesCleaned   = false;

    public function handle(): int
    {
        $this->line('');
        $this->line('  <fg=red;options=bold>Capyrel Clean</>  <fg=gray>— removes all capyrel-generated code</>');
        $this->line('');

        $all = !$this->option('models') && !$this->option('controllers')
            && !$this->option('views') && !$this->option('routes');

        $doModels      = $all || $this->option('models');
        $doControllers = $all || $this->option('controllers');
        $doViews       = $all || $this->option('views');
        $doRoutes      = $all || $this->option('routes');

        // Show preview first
        $this->scan($doModels, $doControllers, $doViews, $doRoutes);

        if ($this->option('dry-run')) {
            $this->line('  <fg=yellow>Dry run — nothing was changed.</>');
            return self::SUCCESS;
        }

        if (!$this->option('force')) {
            $this->line('');
            if (!$this->confirm('  This will remove all capyrel-generated code. Continue?', false)) {
                $this->line('  Aborted.');
                return self::SUCCESS;
            }
        }

        $this->line('');
        $this->runClean($doModels, $doControllers, $doViews, $doRoutes);

        $this->line('');
        $this->line('  <fg=green;options=bold>✔ Capyrel clean complete.</>');
        $this->line("  <fg=gray>  {$this->modelsClean} model(s) cleaned · {$this->controllersClean} controller(s) removed · {$this->viewsClean} view dir(s) removed · routes " . ($this->routesCleaned ? 'cleaned' : 'unchanged') . "</>");
        $this->line('');

        return self::SUCCESS;
    }

    // ── Scan ─────────────────────────────────────────────────────────────────

    private function scan(bool $models, bool $controllers, bool $views, bool $routes): void
    {
        if ($models) {
            foreach (glob(app_path('Models/*.php')) as $f) {
                if (str_contains(file_get_contents($f), '// capyrel:')) {
                    $this->line("  <fg=yellow>⚠ Model:</> " . basename($f) . " <fg=gray>(has injected methods)</>");
                }
            }
        }

        if ($controllers) {
            foreach (glob(app_path('Http/Controllers/*.php')) as $f) {
                if (str_contains(file_get_contents($f), '// capyrel:')) {
                    $this->line("  <fg=yellow>⚠ Controller:</> " . basename($f) . " <fg=gray>(generated by capyrel)</>");
                }
            }
        }

        if ($views) {
            foreach (glob(resource_path('views/*/index.blade.php')) as $f) {
                $dir = dirname($f);
                if ($this->isCapyrelViewDir($dir)) {
                    $this->line("  <fg=yellow>⚠ Views:</> " . basename($dir) . "/ <fg=gray>(generated by capyrel)</>");
                }
            }
        }

        if ($routes && file_exists(base_path('routes/web.php'))) {
            if (str_contains(file_get_contents(base_path('routes/web.php')), '// capyrel:')) {
                $this->line("  <fg=yellow>⚠ Routes:</> routes/web.php <fg=gray>(has capyrel route block)</>");
            }
        }
    }

    // ── Execute ───────────────────────────────────────────────────────────────

    private function runClean(bool $models, bool $controllers, bool $views, bool $routes): void
    {
        if ($models)      $this->cleanModels();
        if ($controllers) $this->cleanControllers();
        if ($views)       $this->cleanViews();
        if ($routes)      $this->cleanRoutes();
    }

    private function cleanModels(): void
    {
        foreach (glob(app_path('Models/*.php')) as $file) {
            $content  = file_get_contents($file);
            if (!str_contains($content, '// capyrel:')) continue;

            // Remove each capyrel-generated method block
            // Matches: blank line + // capyrel: comment + public function ... { ... }
            $cleaned = preg_replace(
                '/\n\n\s+\/\/ capyrel:[^\n]*\n\s+public function \w+\([^)]*\)[^{]*\{[^}]*\}/s',
                '',
                $content
            );

            if ($cleaned !== $content) {
                file_put_contents($file, $cleaned);
                $this->line("  <fg=green>✔ Cleaned model:</> " . basename($file));
                $this->modelsClean++;
            }
        }
    }

    private function cleanControllers(): void
    {
        foreach (glob(app_path('Http/Controllers/*.php')) as $file) {
            $content = file_get_contents($file);
            if (!str_contains($content, '// capyrel:')) continue;

            // A fully generated controller always has the index eager-load marker
            $isGenerated = str_contains($content, '// capyrel: eager loads all detected relations')
                        || str_contains($content, '// capyrel: nested controller');

            if ($isGenerated) {
                unlink($file);
                $this->line("  <fg=green>✔ Removed controller:</> " . basename($file));
                $this->controllersClean++;
            } else {
                // Injected into existing controller — just remove the marker line
                $cleaned = str_replace("// capyrel: eager loading injected\n", '', $content);
                file_put_contents($file, $cleaned);
                $this->line("  <fg=green>✔ Restored controller:</> " . basename($file));
                $this->controllersClean++;
            }
        }
    }

    private function cleanViews(): void
    {
        foreach (glob(resource_path('views/*/')) as $dir) {
            if (!$this->isCapyrelViewDir($dir)) continue;

            $this->deleteDirectory($dir);
            $this->line("  <fg=green>✔ Removed view directory:</> " . basename(rtrim($dir, '/')));
            $this->viewsClean++;
        }
    }

    private function cleanRoutes(): void
    {
        $path = base_path('routes/web.php');
        if (!file_exists($path)) return;

        $content = file_get_contents($path);
        if (!str_contains($content, '// capyrel:')) return;

        // Remove the capyrel route block
        $cleaned = preg_replace(
            '/\n\/\/ capyrel: generated resource routes\nRoute::middleware\(\[\'[^\']+\'\]\)->group\(function \(\) \{[^}]+\}\);\n?/',
            '',
            $content
        );

        if ($cleaned !== $content) {
            file_put_contents($path, $cleaned);
            $this->line("  <fg=green>✔ Cleaned:</> routes/web.php");
            $this->routesCleaned = true;
        }
    }

    private function isCapyrelViewDir(string $dir): bool
    {
        $blades = glob("{$dir}*.blade.php");
        if (empty($blades)) return false;

        $hits = 0;
        foreach ($blades as $blade) {
            $content = file_get_contents($blade);

            // New files (v1.6.0+): stamp is on line 1
            // Old files (pre-v1.6.0): markers are embedded anywhere in the file
            $isCapyrel = str_contains($content, 'capyrel:generated')
                      || str_contains($content, '{{-- capyrel:')
                      || str_contains($content, 'capyrel: relationship usage')
                      || str_contains($content, 'capyrelOpenDelete')   // BS modal helper
                      || str_contains($content, 'open-create')          // Alpine event
                      || str_contains($content, 'createOffcanvas');     // BS offcanvas id

            if ($isCapyrel) $hits++;
        }

        // Majority of blades in this dir are capyrel-generated
        return $hits >= max(1, intdiv(count($blades), 2));
    }

    private function deleteDirectory(string $dir): void
    {
        foreach (glob("{$dir}*") as $file) {
            is_dir($file) ? $this->deleteDirectory($file . '/') : unlink($file);
        }
        @rmdir(rtrim($dir, '/'));
    }
}
