<?php

namespace Julio\Capyrel\Commands;

use Illuminate\Console\Command;
use Julio\Capyrel\UI\UiAdapterRegistry;

/**
 * php artisan capyrel:ui:cache
 *
 * Pre-warms the adapter registry for production by writing a bootstrap
 * cache file to bootstrap/cache/capyrel-ui.php.
 *
 * php artisan capyrel:ui:cache:clear  — removes the cache file.
 */
class UiCacheCommand extends Command
{
    protected $signature = 'capyrel:ui:cache
                            {--clear : Remove the cache file instead of generating it}';

    protected $description = 'Pre-warm the Capyrel UI adapter registry for production';

    private string $cachePath;

    public function __construct(private UiAdapterRegistry $registry)
    {
        parent::__construct();
        $this->cachePath = base_path('bootstrap/cache/capyrel-ui.php');
    }

    public function handle(): int
    {
        $this->line('');
        $this->line('  <fg=cyan;options=bold>Capyrel UI Cache</>');
        $this->line('');

        if ($this->option('clear')) {
            return $this->clearCache();
        }

        return $this->buildCache();
    }

    // ─────────────────────────────────────────────────────────────────

    private function buildCache(): int
    {
        $adapters = $this->registry->all();

        if (empty($adapters)) {
            $this->warn('  No adapters found — cache not written.');
            return self::FAILURE;
        }

        $entries = [];

        foreach ($adapters as $name => $adapter) {
            $class = get_class($adapter);
            $entries[$name] = [
                'class'        => $class,
                'capabilities' => $adapter->capabilities(),
            ];

            $this->line("  <fg=green>✔</> <fg=white>{$name}</> → <fg=gray>{$class}</>");
        }

        $defaultAdapter = $this->registry->defaultName();
        $modelAdapters  = config('capyrel.ui.model_adapters', []);

        $php = $this->renderCacheFile($entries, $defaultAdapter, $modelAdapters);

        $cacheDir = dirname($this->cachePath);
        if (!is_dir($cacheDir)) {
            mkdir($cacheDir, 0755, true);
        }

        file_put_contents($this->cachePath, $php);

        $this->line('');
        $this->line("  <fg=green;options=bold>Cache written to:</> bootstrap/cache/capyrel-ui.php");
        $this->line("  <fg=gray>" . count($entries) . " adapter(s) cached.</>");
        $this->line('');

        return self::SUCCESS;
    }

    private function clearCache(): int
    {
        if (! file_exists($this->cachePath)) {
            $this->line('  <fg=gray>Cache file does not exist — nothing to clear.</>');
            return self::SUCCESS;
        }

        unlink($this->cachePath);
        $this->line('  <fg=green>✔</> Cache cleared.');
        $this->line('');

        return self::SUCCESS;
    }

    private function renderCacheFile(array $entries, string $default, array $modelAdapters): string
    {
        $entriesExport   = var_export($entries, true);
        $modelMapExport  = var_export($modelAdapters, true);
        $generatedAt     = now()->toIso8601String();

        return <<<PHP
        <?php

        /**
         * Capyrel UI adapter registry cache.
         * Generated at: {$generatedAt}
         *
         * This file is auto-generated by `php artisan capyrel:ui:cache`.
         * Do not edit manually — re-run the command to refresh.
         */

        return [
            'generated_at'   => '{$generatedAt}',
            'default'        => '{$default}',
            'model_adapters' => {$modelMapExport},
            'adapters'       => {$entriesExport},
        ];
        PHP;
    }
}
